### ISSUE TITLE
Add configurable folder path to upload to S3

### ISSUE THREAD

**Issue by djhouseknecht** [Jefiozie/ngx-aws-deploy#102]
I'm new to S3 and buckets. I stumbled upon `ngx-aws-deploy` over the weekend and love it! Made deploying my first app super easy. I wanted to request a feature (not sure if it is possible or not)

## Feature Request
I have a use case that could be solved by having a configurable folder path to pass into `ngx-aws-deploy`'s config. 

* I am using [scully.io](https://github.com/scullyio/scully) to generate some static content. My angular build goes to `dist/my-app` and my scully build goes to `dist/static`. Having an option to tell `ngx-aws-deploy` what directory to upload would be awesome. 

If that was possible, I could then even set up versioning in my bucket for organization and rollback capabilities using scripts. 

Let me know if that isn't possible given angular's cli apis or other blockers.

**Comment by Jefiozie** [comment]
Hi @djhouseknecht, thank you for this issue! Technically I think we could find a way how to do this. However, I'm seeing a problem with the way how builders (in this case a deploy builder) works. Normally you have two ways with `ng deploy`. 

1. you run `ng deploy` it will start a new build and use the freshly generated files to upload.
2. you run `ng deploy --no-build` and it will skip the build and publish the files that are on the `outputpath` of the project.

As Scully is a separate `process` that is not directly linked to the `Angular CLI` tooling I'm not sure how we easily can adopt your feature request without having to work around the basics of the `builders` idea.

Any thoughts around this? I would love to hear them.

**Comment by djhouseknecht** [comment]
@Jefiozie, yeah I agree with you. I looked through some of your code and some docs on Angular Builders and realized there probably wasn't a clean way to do this within the bounds of a builder. 

There are probably "hacky" ways to get around the builder, but that at that point it may as well be a separate library. I think this issue can be closed since it isn't really possible with the current builder best practices. 

Thanks for the discussion, though!
