### ISSUE TITLE
feat : allow aws secrets to be passed via environment

### ISSUE THREAD

**Issue by beaussart** [Jefiozie/ngx-aws-deploy#12]
Putting aws keys directly in the angular json, accessible to all the devs is like giving them all the secret key.

I think users should be allowed to pass it via env.

**Comment by Jefiozie** [comment]
Thanks @beaussart, I already thought about this as a new feature. Do you like making a PR for this?

**Comment by beaussart** [comment]
I can maybe do it tomorrow, will keep you posted :)
