### ISSUE TITLE
[Discussion] Who is using ngx-aws-deploy in production apps

### ISSUE THREAD

**Issue by Jefiozie** [Jefiozie/ngx-aws-deploy#129]
I'm curious to see how many companies are really using this in production.

Leave a comment if you would like! 🙏🏻

**Comment by azamanaza** [comment]
I'm currently looking into this. If we're happy, we'll let you know. :)

**Comment by rlmestre** [comment]
Looking into this as well if we can get some issues out of the way ;)

**Comment by Jefiozie** [comment]
>Looking into this as well if we can get some issues out of the way ;)

I'm open for feedback if you have feedback please submit an issue for it and we can discuss the points you are missing.

**Comment by lindhard** [comment]
If we could set meta-data when uploading then we would use it for production but right now it's only used for testing and staging.

**Comment by Jefiozie** [comment]
Hey @lindhard, thanks for your response. 
Would you mind making an issue for this I think it is a nice addition that people can use optional? Would you be willing to make a PR for this? I'm more than happy to assist you to create one.

**Comment by lindhard** [comment]
@Jefiozie of course - Monday next week you will get 2 issues from me! :-)
Enjoy the weekend, if you get the chance!

**Comment by thomasturrell** [comment]
We are at Berry Cloud.

ngx-aws-deploy is a really useful project. We could have rolled our own solution but this is neater. 

We still use the ASW CLI to invalidate our CloudFront distribution but it's not too much of a problem.

**Comment by Jefiozie** [comment]
Closing this in favor of Github Discussions.
