### ISSUE TITLE
ng deploy command not working

### ISSUE THREAD

**Issue by rajeshyadavdotnet** [Jefiozie/ngx-aws-deploy#168]
**Describe the bug**
Rajeshs-MacBook-Air:www.RajeshYadav.net raj$ ng deploy
Your global Angular CLI version (9.1.5) is greater than your local
version (8.1.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The specified command ("deploy") is invalid. For a list of available options,
run "ng help".

Did you mean "doc"?
Rajeshs-MacBook-Air:www.RajeshYadav.net raj$ 

angular.json
   "deploy": {
          "builder": "@jefiozie/ngx-aws-deploy:deploy",
          "options": {
            "region": "ap-south-1",
            "bucket": "rajeshkumaryadav.com",
            "secretAccessKey": "my secret key is here I put",
            "accessKeyId": "here i put access key"
          }
        }

**Comment by rajeshyadavdotnet** [comment]
Issue fixed, the issue was angular 8, when I upgrade to angular 9 then all worked.

Upload is fine but when uploading with ng deploy then s3 is broken-

403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: 75EA3AB9A8EF89C0
HostId: N+dFicu+wTwwjtjze7X/H3Zn6pE4Cr07cXf08BHm0snjFim9IkGPvQOOJapfQXQK/08MVkt1GVk=

**Comment by rajeshyadavdotnet** [comment]
I noticed that, when I am uploading the dist folders contents manually by drag and drop then it gives me option for permission as shown below -
<img width="1167" alt="Screenshot 2020-05-22 at 17 35 13" src="https://user-images.githubusercontent.com/12113699/82689874-12cf1000-9c53-11ea-8c3a-e7d9eace1c14.png">

When select last option and click next and run url http://rajeshkumaryadav.com/ or http://rajeshkumaryadav.com.s3-website.ap-south-1.amazonaws.com/ all works fine.

When I use automation by doing ng deploy, then ng build happens, files generation happens in dist which is fine and normal and after that your package connects with my s3 and deploys the file which is also fine.

BUT your api is not setting the correct permission.

and thus I am getting error - 
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: 75EA3AB9A8EF89C0
HostId: N+dFicu+wTwwjtjze7X/H3Zn6pE4Cr07cXf08BHm0snjFim9IkGPvQOOJapfQXQK/08MVkt1GVk=

Can you please help me on this?

**Comment by rajeshyadavdotnet** [comment]
Hi,

After spending few minutes on google I found below bucket policy -

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::rajeshkumaryadav.com/*"
            ]
        }
    ]
}

When applied, my site started working fine instead of 403 error.

Please do let me know if anyone has better solution.

**Comment by Jefiozie** [comment]
Hi @rajeshyadavdotnet, thank you for submitting the issue. I think the issue you are facing is an issue with the permissions within AWS S3.  The setup of permissions within AWS S3 is out of the scope of this package (at least for now). 

For now, I'm going to close this issue. If you find an issue with the package itself I'm more then happy to help you. Please follow the issue guidelines so that people easily can reproduce the issue and try to solve the issue. Thanks for this.
