### ISSUE TITLE
deploy with default configuration instead of production

### ISSUE THREAD

**Issue by make-ing** [Jefiozie/ngx-aws-deploy#170]
Hello its me again... i'm a noob when i comes to node.js and angular but i have to deploy the app with the default (environment.ts) environment file instead of the production one (environment.prod.ts). I found the this code https://github.com/Jefiozie/ngx-aws-deploy/blob/dfc2babafaf8bfeb5b13f58a867b1a816d304658/builder/deploy/index.ts#L35 which probaply chooses the environment, but how can i set it? if i call
```ng deploy``` it deploys the production environment which according to the line i linked is fine... But how can i force it now to use the ```environment.ts``` file instead of  the ```environment.prod.ts``` file?

Thank you very much for your help allready 🍕!

**Comment by Jefiozie** [comment]
Hey @make-ing , I'm working on this in #173 would you help me to see if this will resolve your problem?

**Comment by Jefiozie** [comment]
This issue is closed with the latest release.

**Comment by make-ing** [comment]
sorry for responding so late... i will have a look at it... thank you very much.
