### ISSUE TITLE
Make release easier by using a tool like semantic-release or anything else

### ISSUE THREAD

**Issue by Jefiozie** [Jefiozie/ngx-aws-deploy#2]

**Comment by StefanNieuwenhuis** [comment]
Hey Jeffrey,

What do you want to improve on the release process exactly?
Maybe I can help you with it :) 

- Stefan

**Comment by Jefiozie** [comment]
Hey Stefan, 

As you can see I have two folder, the builder and the builder-test(app). Atm I need to manual push and publish new releases to Github and npm. This is something I would like to improve. 

Some requirements I would love to see:

1. Changelog based on commits
2. Versioning based on the commits
3. Copy the README & License to the Builder folder.
4. Publish to Github (tag & release) en publish it to NPM.


If possible I also would love to run the test however yesterday I had some issues with that using Github Actions.

**Comment by Jefiozie** [comment]
Btw, I have already some simple npm scripts for copying and atm I just use "standard-version" for the versioning and changelog. However fill free to purpose a solution, I'm not hooked to a specific way or tool.

**Comment by StefanNieuwenhuis** [comment]
And do you want to hook it to CI/CD? If so, which one do you want to use?
I think [`semantic-release`](https://github.com/semantic-release/semantic-release) would be a good option for _automatic_ releases (combined w/ CI/CD).

**Comment by Jefiozie** [comment]
I think for now I still would like to do a manual trigger on the publishing process, is this possible with `semantic-release`?
As CI/CD I like Github Actions but Circle CI is also good.
