### ISSUE TITLE
How to use security environment variable?

### ISSUE THREAD

**Issue by rikimm** [Jefiozie/ngx-aws-deploy#288]
I have doubts how to use this NG_DEPLOY_AWS_ACCESS_KEY_ID, NG_DEPLOY_AWS_SECRET_ACCESS_KEY, NG_DEPLOY_AWS_BUCKET and NG_DEPLOY_AWS_REGION., If you have any example.

Regards

**Comment by Jefiozie** [comment]
Hi @rikimm,

Great question, my answer on this is "it depends". It depends on where you would like to run the deploy.
On my local machine, I have an extra npm script with `cross-env` where I set the environment variables.

```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "deploy": "npx cross-env NG_DEPLOY_AWS_ACCESS_KEY_ID=<YOUR_ACCESS_KEY> NG_DEPLOY_AWS_SECRET_ACCESS_KEY=<YOUR_SECRET> ng deploy"
  },
```

If you are looking at a way to do this in your CI, I would say you need to add ENV variables in your pipeline.
Depending on your needs you can switch variables during specific pipelines, for example, ACC could have the variables for the ACC bucket, etc.

I hope this is answering your question, let me know if you have any questions.
If this is the answer you are looking for, could you close the issue? 

Thanks.

**Comment by rlmestre** [comment]
If the AWS-CLI is configured, the AWS-SDK will get the credentials from there automatically. To me that would be the preferred, much more secure, solution.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html

**Comment by Jefiozie** [comment]
Hi @rlmestre , 

Thanks for your feedback. I'm happy to discuss an alternative approach against the one we use atm. I started this package at some point so people could have the advantage of the AWS infrastructure.  Do you know if we could run the cli from a different program? That would be ideal so that we can leverage some of the `aws-cli` parts.
