### ISSUE TITLE
Uploader ignores files with name starting with dot

### ISSUE THREAD

**Issue by sinarstk** [Jefiozie/ngx-aws-deploy#305]
When there is a folder or a file in the code with dot in the name, the uploader doesn't upload them to s3. Everything is being compiled in dist but not uploaded.

To reproduce:
- Add a folder and name it with a dot in the beginning
- Try to deploy
- Compare your bucket on s3 and dist folder

In some cases, this is necessary especially for adding apple-app-site-association.

I tried Version 1.2.1 and Version 2.0.0
I am using angular 10.

**Comment by Jefiozie** [comment]
Hi @sinarstk, thanks for reporting this issue. Could you tell me if this is happening because of missing configuration with the SDK?
Thanks.

**Comment by sinarstk** [comment]
Hi @Jefiozie, the configuration looks ok and everything seems working as expected. The only issue is folders with dot won't make it to S3. I am able to upload them with AWS CLI.
I found out about this while adding ".well-known" folder for the apple-app-site-association file.

**Comment by aviboy2006** [comment]
Shall i pick this issue for contribution ?

**Comment by Jefiozie** [comment]
Sure, let me know if you need some help.
