### ISSUE TITLE
Version 3.0.0 deployment fails on node 14.15.1

### ISSUE THREAD

**Issue by thomasturrell** [Jefiozie/ngx-aws-deploy#351]
Version 3.0.0 deployment fails on node 14.15.1 and npm 6.14.8 with the following error:

```
Start uploading files...
❌  Looks like you are missing some configuration
❌  Error during files upload
```

1. Install node 14.15.1
2. Verify that npm version is 6.14.8
3. Follow the [quick start guide](https://github.com/Jefiozie/ngx-aws-deploy#quick-start) 
4. See the error

Reproduced on:
- OS: MacOS 
- Version 11.1

and

- OS: Ubuntu 
- Version:  18.04.5 (LTS version)

I have verified that the configuration is present so the error message is misleading.
Version 2.0.1 works with node 14.15.1. Version 3.0.0 works correctly with node version 15.

Because Karma only supports LTS version of node and there is currently an [issue preventing Karma from working on node 15](https://github.com/karma-runner/karma/issues/3571), it might not be possible for all projects to migrate to node 15.

**Comment by Jefiozie** [comment]
HI @thomasturrell, thank you for submitting this issue. I will add some tags to see if somebody from the community will pick this up. Upcoming days I won't have the time to work on this. Feel free if you would like to resolve it. I'm more than happy to do some reviews for you.

**Comment by Jefiozie** [comment]
Hi @thomasturrell , it is been a while, but I just upgraded the package to v12 #378. When the Github actions have run and all checks are ready I'm going to release a beta version.

**Comment by Jefiozie** [comment]
HI @thomasturrell I just published a new beta version I hope this will resolve your issue: https://www.npmjs.com/package/@jefiozie/ngx-aws-deploy/v/4.0.0-beta.0

**Comment by Jefiozie** [comment]
Hi @thomasturrell, I tested this with node v 14.16.1 and npm version 6.14.12 here it looks resolved. Closing this as there will be a release soon.
