### ISSUE TITLE
Why the `NG_DEPLOY_` prefix for the environment variables?

### ISSUE THREAD

**Issue by fkm** [Jefiozie/ngx-aws-deploy#358]
Is there a reason you don't use the official environment variables?
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`

Don't get me wrong. I can write a script that adds the prefixed variables. But I'm curious :smiley: Is this a security consideration?

**Comment by Jefiozie** [comment]
Hi @fkm, great question, when I started with this package I didn't want people to get confused about the environment variables in different projects. If you use the default env variables it can be applied to all projects and can easily be mixed what could result in problems.  By prefixing it, it at least points in the direction of an Angular app. That is the reason, no other security considerations further.

Did this answer your question?

**Comment by fkm** [comment]
> If you use the default env variables it can be applied to all projects and can easily be mixed what could result in problems.

Good point! Thank you for your response.
