### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by e-oz** [Jefiozie/ngx-aws-deploy#380]
Please consider adding CHANGELOG.md file.
I'm trying to find what breaking changes were introduced with the 4.x release and to do this I need to check every commit.

**Comment by e-oz** [comment]
Thank you! 🍒

**Comment by Jefiozie** [comment]
Your welcome, I already published them to [github releases](https://github.com/Jefiozie/ngx-aws-deploy/releases) but I don't know why I didn't make a CHANGELOG fron day one. Thank you for creating the issue and helping me address this.
