### ISSUE TITLE
Invalidate AWS CloudFront distribution after upload to AWS S3

### ISSUE THREAD

**Issue by segfault79** [Jefiozie/ngx-aws-deploy#392]
AWS S3 is very often used with AWS CloudFront as a caching layer.

Currently with this NX plug-in one can upload files to AWS S3 but an AWS CloudFront cache is not changed and may deliver outdated stale files/content.

What do you think about an (optional) invalidation on an AWS CloudFront distribution after the upload to AWS S3? Does this fit in this plugin?

Please give feedback on this. I can take a look at the implementation.

**Comment by aviboy2006** [comment]
It can be option params to pass. Invalidating cache need to keep distribution id under env. Similarly I have done in python code https://github.com/aviboy2006/angular-upload-s3cf

**Comment by Jefiozie** [comment]
I think this would add extra value to this package. I'm looking forward to your PR @segfault79
