### ISSUE TITLE
Package aws-sdk is added as dependency, peerDependency & devDependency

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Jefiozie/ngx-aws-deploy#59]
**Describe the bug**
`aws-sdk` is added as `dependency`, `peerDependency` and `devDependency`.

See [package.json](https://github.com/Jefiozie/ngx-aws-deploy/blob/master/builder/package.json).

**Comment by Jefiozie** [comment]
Thanks 👍  is fixed in a upcoming release
