### ISSUE TITLE
Support upload content-type

### ISSUE THREAD

**Issue by zack9433** [Jefiozie/ngx-aws-deploy#71]
https://github.com/aws/aws-sdk-js/issues/2510

https://github.com/aws/aws-sdk-js/issues/3085

**Comment by Jefiozie** [comment]
Hi @zack9433, thank you for the issue. Could you describe the use case you would like us to implement? Is it just a way to set the content-type? Or should it be the content type of the file?

**Comment by zack9433** [comment]
@Jefiozie In my case, I am able to upload my web application to s3 but every file default content-type is application/octet-stream includes index.html and browser will download index.html as a file.

If I manually change content-type to text/html for index.html and browser can render page correctly.

**Comment by Jefiozie** [comment]
Hi, @zack9433 forgot to ask but would you like to make the PR? I would love to see a fix for this issue. Let me know if you need any help!
