### ISSUE TITLE
Using NoBuild options will stop deployment process

### ISSUE THREAD

**Issue by Jefiozie** [Jefiozie/ngx-aws-deploy#83]
**Describe the bug**
When adding the no-build flag as an option the deployment will not run.

**To Reproduce**
1. Create a prod build by running `ng build --prod`
2. Run `ng deploy --no-build`
3.  You will be provided with a success message but no upload has been done

**Expected behavior**
When using the --no-build error it will need to look at the output path of the target and upload the content of the output path.

**Comment by erwinverboekend** [comment]
Hi Jeffrey,

Are you planning to make a pr yourself? Maybe I can help if you want some help :)

**Comment by Jefiozie** [comment]
Hi @erwinverboekend, I would appreciate it if you are willing to help me 🙏. If you need my help in any way just send me a ping. Looking forward to your PR.

**Comment by Jefiozie** [comment]
This is closed with our latest version.
